### ISSUE TITLE
Feature: User can view home page

### ISSUE THREAD

**Issue by NicholasProdehl** [NicholasProdehl/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view home page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will be able to view all posts in chronological order. The side-bar on the left allows user to decide between home, the new post page, and the people/users page. On the top right, you can look at your own users page. Any posts on the home page, you can edit if it's your own.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="358" alt="Screen Shot 2022-01-05 at 10 21 15 AM" src="https://user-images.githubusercontent.com/90858352/148268615-b52e3702-b470-4be8-a25b-03e0019ef5c3.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to database schema
- [ ] Update `data.sql` to database preloaded data

### ☁️ Server

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a Home component for the home page.
- [ ] Create a 

- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] Create button elements for side-bar
- [ ] Create css for button elements on side-bar
- [ ] Create header elements, including the current user state.
- [ ] create posts header
- [ ] line up CSS so everything is positioned properly
- [ ] deal with making it move around properly
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
